---
driver:
  name: docker
  hostname: nginx.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: nginx
  grains:
    noservices: True
  dependencies:
    - name: horizon
      repo: git
      source: https://github.com/salt-formulas/salt-formula-horizon
  state_top:
    base:
      "*":
        - nginx
  pillars:
    top.sls:
      base:
        "*":
          - nginx

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: horizon_no_ssl
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/horizon_no_ssl.sls

  - name: horizon_with_ssl
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/horizon_with_ssl.sls

  - name: horizon_with_ssl_options
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/horizon_with_ssl_options.sls

  - name: proxy
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/proxy.sls

  - name: proxy-rate-limit
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/proxy_rate_limit.sls

  - name: redirect
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/redirect.sls

  - name: static
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/static.sls

  - name: stats
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/stats.sls

  - name: proxy_with_ssl
    provisioner:
      pillars-from-files:
        nginx.sls: tests/pillar/proxy_with_ssl.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
